baseURL = '//www.jeclark.net/'
languageCode = 'en-us'
title = 'Josh Clark'
theme= 'digitalgarden'

googleAnalytics = "G-1KE8LGXJ1J"

[menu]
[[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
[[menu.main]]
    name = 'Content'
    params.header = true
    weight = 2
[[menu.main]]
    name = 'All Articles'
    url = '/articles'
    weight = 3
[[menu.main]]
    name = 'Articles by Topic'
    params.header = true
    weight = 3
[[menu.main]]
    name = 'Troubleshooting'
    url = '/tags/troubleshooting'
    weight = 4
[[menu.main]]
    name = 'Wireshark'
    url = '/tags/wireshark'
    weight = 4
[[menu.main]]
    name = 'Performance'
    url = '/tags/performance'
    weight = 4
[[menu.main]]
    name = 'Other'
    url = '/tags/other'
    weight = 4



[[menu.social]]
    name = 'LinkedIn'
    url = 'https://www.linkedin.com/in/je-clark/'
    weight = 1
[[menu.social]]
    name = 'GitHub'
    url = 'https://github.com/je-clark'
    weight = 1 
[[menu.social]]
    name = 'Email'
    url = 'mailto:hello@jeclark.net'
    weight = 1